import { INodeProperties } from 'n8n-workflow';

export const placeOrderProperties: INodeProperties[] = [
	{
		displayName: 'Symbol Name or ID',
		name: 'symbol',
		type: 'options',
		required: true,
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
		displayOptions: { show: { resource: ['order'], operation: ['placeOrder'] } },
		typeOptions: { loadOptionsMethod: 'getSymbols' },
		options: [],
		default: '',
	},
	{
		displayName: 'Side',
		name: 'side',
		type: 'options',
		required: true,
		displayOptions: { show: { resource: ['order'], operation: ['placeOrder'] } },
		options: [
			{ name: 'Buy', value: 'BUY' },
			{ name: 'Sell', value: 'SELL' },
		],
		default: 'BUY',
		description: 'Order side',
	},
	{
		displayName: 'Order Type',
		name: 'orderType',
		type: 'options',
		required: true,
		displayOptions: { show: { resource: ['order'], operation: ['placeOrder'] } },
		options: [
			{ name: 'Market', value: 'MARKET' },
			{ name: 'Limit', value: 'LIMIT' },
			{ name: 'Stop', value: 'STOP' },
			{ name: 'Stop Market', value: 'STOP_MARKET' },
			{ name: 'Take Profit', value: 'TAKE_PROFIT' },
			{ name: 'Take Profit Market', value: 'TAKE_PROFIT_MARKET' },
			{ name: 'Trailing Stop Market', value: 'TRAILING_STOP_MARKET' },
		],
		default: 'MARKET',
		description: 'Type of order',
	},
	{
		displayName: 'Quantity',
		name: 'quantity',
		type: 'number',
		required: true,
		displayOptions: { show: { resource: ['order'], operation: ['placeOrder'] } },
		typeOptions: { numberPrecision: 8 },
		default: 0,
		description: 'Order quantity',
	},
	{
		displayName: 'Price',
		name: 'price',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['order'],
				operation: ['placeOrder'],
				orderType: ['LIMIT', 'STOP', 'TAKE_PROFIT'],
			},
		},
		typeOptions: { numberPrecision: 8 },
		default: 0,
		description: 'Order price (required for LIMIT, STOP, TAKE_PROFIT)',
	},
	{
		displayName: 'Stop Price',
		name: 'stopPrice',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['order'],
				operation: ['placeOrder'],
				orderType: ['STOP', 'STOP_MARKET', 'TAKE_PROFIT', 'TAKE_PROFIT_MARKET'],
			},
		},
		typeOptions: { numberPrecision: 8 },
		default: 0,
		description: 'Stop price (required for STOP, STOP_MARKET, TAKE_PROFIT, TAKE_PROFIT_MARKET)',
	},
	{
		displayName: 'Callback Rate %',
		name: 'callbackRate',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['order'],
				operation: ['placeOrder'],
				orderType: ['TRAILING_STOP_MARKET'],
			},
		},
		typeOptions: { minValue: 0.1, maxValue: 5, numberPrecision: 1 },
		default: 1,
		description: 'Callback rate for trailing stop (0.1 to 5)',
	},
	{
		displayName: 'Time in Force',
		name: 'timeInForce',
		type: 'options',
		displayOptions: {
			show: {
				resource: ['order'],
				operation: ['placeOrder'],
				orderType: ['LIMIT', 'STOP', 'TAKE_PROFIT'],
			},
		},
		options: [
			{ name: 'GTC', value: 'GTC' },
			{ name: 'IOC', value: 'IOC' },
			{ name: 'FOK', value: 'FOK' },
			{ name: 'GTX Post Only', value: 'GTX' },
		],
		default: 'GTC',
		description: 'Time in force policy',
	},
	{
		displayName: 'Working Type',
		name: 'workingType',
		type: 'options',
		displayOptions: {
			show: {
				resource: ['order'],
				operation: ['placeOrder'],
				orderType: ['STOP', 'STOP_MARKET', 'TAKE_PROFIT', 'TAKE_PROFIT_MARKET', 'TRAILING_STOP_MARKET'],
			},
		},
		options: [
			{ name: 'Mark Price', value: 'MARK_PRICE' },
			{ name: 'Contract Price', value: 'CONTRACT_PRICE' },
		],
		default: 'CONTRACT_PRICE',
		description: 'Stop price working type',
	},
	{
		displayName: 'Reduce Only',
		name: 'reduceOnly',
		type: 'boolean',
		displayOptions: { show: { resource: ['order'], operation: ['placeOrder'] } },
		default: false,
		description: 'Whether the order is reduce only',
	},
	{
		displayName: 'Client Order ID',
		name: 'clientOrderId',
		type: 'string',
		displayOptions: { show: { resource: ['order'], operation: ['placeOrder'] } },
		default: '',
		description: 'A unique ID for the order (optional)',
	},
];
